//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ts.api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ts.api.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with given email already exists.
        /// </summary>
        public static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calling Eve Api. Possibly wrong access mask for the key.
        /// </summary>
        public static string ErrorAccessMask {
            get {
                return ResourceManager.GetString("ErrorAccessMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failure. Invalid key and/or verification code.
        /// </summary>
        public static string ErrorAuthenticationFailure {
            get {
                return ResourceManager.GetString("ErrorAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failure. Invalid key {0} and/or verification code.
        /// </summary>
        public static string ErrorAuthenticationFailureWithKey {
            get {
                return ResourceManager.GetString("ErrorAuthenticationFailureWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calling Eve Api.
        /// </summary>
        public static string ErrorCallingEveApi {
            get {
                return ResourceManager.GetString("ErrorCallingEveApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided key is already defined.
        /// </summary>
        public static string ErrorKeyAlreadyDefined {
            get {
                return ResourceManager.GetString("ErrorKeyAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has expired.
        /// </summary>
        public static string InvalidSessionKey {
            get {
                return ResourceManager.GetString("InvalidSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user/password.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityException.
        /// </summary>
        public static string SecurityException {
            get {
                return ResourceManager.GetString("SecurityException", resourceCulture);
            }
        }
    }
}
